version: "3.8"

networks:
  node-project:
    driver: bridge

volumes:
  my-mySQL:
    name: my-mySQL


services:


  mySQL:
    image: mysql:8.0
    volumes:
      - my-mySQL:/usr/var/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: testUser
      MYSQL_PASSWORD: 1234567
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    restart: always
    ports:
      - "3306:3306"
    tty: true
    networks:
      - node-project
  
   

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mySQL
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8086:80"
    networks:
      - node-project

  
